export const styles = {
  controlButton: {
    padding: "10px",
    border: "none",
    cursor: "pointer",
    fontWeight: "bold",
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 9999,
  },
  addMediaModal: {
    background: "#fff",
    padding: "20px",
    borderRadius: "4px",
    maxWidth: "400px",
  },
  addMediaCloseButton: {
    background: "red",
    color: "#fff",
    border: "none",
    padding: "8px 12px",
    borderRadius: "4px",
    cursor: "pointer",
    margin: "8px",
    marginLeft: "0px",
  },
  addMediaButton: {
    background: "#4BB543",
    color: "#fff",
    border: "none",
    padding: "8px 12px",
    borderRadius: "4px",
    cursor: "pointer",
    margin: "8px",
  },
  error: {
    color: "red",
    marginTop: "10px",
  },
};
