export const styles = {
  modal: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: "1",
  },
  modalContent: {
    backgroundColor: "#fff",
    padding: "20px",
    height: "50vh",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "column",
    overflow: "auto",
    margin: "1rem",
  },
  modalBody: {
    width: "100%",
    height: "90%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
    padding: "10px",
  },
  modalHeader: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
  },
  closeButton: {
    padding: "10px",
    border: "none",
    cursor: "pointer",
    fontWeight: "bold",
    backgroundColor: "#eee",
  },
};
