export const styles = {
  controlButton: {
    padding: "10px",
    border: "none",
    cursor: "pointer",
    fontWeight: "bold",
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 9999,
  },
  shareModal: {
    background: "#fff",
    padding: "30px",
    borderRadius: "4px",
    maxWidth: "500px",
    width: "100%",
    boxSizing: "border-box",
    boxShadow: "0 0 10px rgba(0, 0, 0, 0.2)",
  },
  shareTitle: {
    marginBottom: "20px",
    fontWeight: "bold",
  },
  shareOptionsList: {
    listStyle: "none",
    padding: 0,
    margin: "10px 0",
  },
  shareOption: {
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    padding: "10px",
    margin: "5px 0",
    borderRadius: "4px",
    background: "#f5f5f5",
  },
  closeButtonDiv: {
    display: "flex",
    justifyContent: "flex-end",
    marginTop: "20px",
  },
  shareCloseButton: {
    padding: "10px 20px",
    border: "none",
    borderRadius: "4px",
    marginRight: "10px",
    cursor: "pointer",
    background: "#ff4d4f",
    color: "#fff",
    fontWeight: "bold",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.2)",
  },
  error: {
    color: "red",
    marginTop: "10px",
  },
};
